//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ongen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ongen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;
        ///-
        ///,
        ///.
        ////
        ///[
        ///\
        ///]
        ///`
        ///=
        ///0
        ///1
        ///2
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///A
        ///ALT
        ///B
        ///BACKSPACE
        ///C
        ///CAPSLOCK
        ///CTRL
        ///D
        ///DEL
        ///DOWNARROW
        ///E
        ///END
        ///ENTER
        ///ESCAPE
        ///F
        ///F1
        ///F10
        ///F11
        ///F12
        ///F2
        ///F3
        ///F4
        ///F5
        ///F6
        ///F7
        ///F8
        ///F9
        ///G
        ///H
        ///HOME
        ///I
        ///INS
        ///J
        ///K
        ///KP_5
        ///KP_DEL
        ///KP_DOWNARROW
        ///KP_END
        ///KP_ENTER
        ///KP_HOME
        ///KP_INS
        ///KP_LEFTARROW
        ///KP_MINUS
        ///KP_MULTIPLY
        ///KP_PGDN
        ///KP_PGUP
        ///KP_PLUS
        ///KP_RIGHTARROW
        ///KP_SLASH
        ///KP_UPARROW
        ///L
        ///LEFTARROW
        ///LWIN
        ///M
        ///MOUSE1
        ///MOUSE2
        ///MOUSE3
        ///MOUSE4
        ///MOUSE5
        ///MWHEELDOWN
        ///MWHEELUP
        ///N
        ///NUMLOCK
        ///O
        ///P
        ///PGDN
        ///PGUP
        ///Q
        ///R
        ///RCTR [rest of string was truncated]&quot;;.
        /// </summary>
        public static string keys {
            get {
                return ResourceManager.GetString("keys", resourceCulture);
            }
        }
    }
}
